### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell -S priv,deps`

### CODE REVIEW

**Comment by kipcole9** [comment]
🥳🥳🥳🥳🥳

Thanks as always!

**Comment by kianmeng** [comment]
:tada: :tada: :tada: :tada: :tada:

**Comment by kianmeng** [comment]
@kipcole9 Let me know if you want me to add GitHub Actions CI, I've noticed this repo don't have any? Maybe there is a good reason for it?

**Comment by kipcole9** [comment]
On all the CI systems I've tried (cirrus etc) the compile times for Cldr and Unicode projects has always been too long.

I have my own private Jenkins setup that runs CI on each push but I would like to get away from that if I can.

Perhaps the limits on GitHub actions are more relaxed?

For sure I would welcome a contribution to give that a try!

**Pull request merged**
